package com.promptu.script.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Guy on 28/12/2016.
 */
public class CLIForm {
    private JTabbedPane tabbedPane1;
    private JPanel panel1;
    private JButton newTabBtn;

    private int sessionCount = 0;

    public CLIForm() {

        while (tabbedPane1.getTabCount() > 0)
            tabbedPane1.removeTabAt(0);

        newTabBtn.addActionListener(e -> {
            sessionCount++;
            String title = "Session " + sessionCount;
            tabbedPane1.addTab(title, new CLITab().getRootComponent());
            int index = tabbedPane1.indexOfTab(title);

            JPanel tabPane = new JPanel(new GridBagLayout());
            tabPane.setOpaque(false);
            JLabel titleLbl = new JLabel(title);
            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            tabPane.add(titleLbl, gbc);
            gbc.gridx++;
            gbc.weightx = 0;
            tabPane.add(btnClose, gbc);

            tabbedPane1.setTabComponentAt(index, tabPane);
            btnClose.addActionListener(new CloseActionHandler(title));
        });

    }

    public Container root() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        tabbedPane1.setTabLayoutPolicy(1);
        panel1.add(tabbedPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Untitled", panel2);
        final JToolBar toolBar1 = new JToolBar();
        panel1.add(toolBar1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        newTabBtn = new JButton();
        newTabBtn.setText("New CLI Session");
        toolBar1.add(newTabBtn);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public class CloseActionHandler implements ActionListener {

        private String tabName;

        public CloseActionHandler(String tabName) {
            this.tabName = tabName;
        }

        public void actionPerformed(ActionEvent evt) {
            int index = tabbedPane1.indexOfTab(tabName);
            if (index >= 0)
                tabbedPane1.removeTabAt(index);
        }

    }

}
