package com.promptu.script.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.promptu.script.ScriptEngine;
import org.fife.ui.autocomplete.AutoCompletion;
import org.fife.ui.autocomplete.BasicCompletion;
import org.fife.ui.autocomplete.CompletionProvider;
import org.fife.ui.autocomplete.DefaultCompletionProvider;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Set;

/**
 * Created by Guy on 28/12/2016.
 */
public class CLITab {
    private JPanel panel1;
    private JTextArea cliIn;
    private JTextArea cliOut;
    private JButton submitBtn;

    public CLITab() {

        ActionListener submitListener = e -> {
            String t = cliOut.getText();
            t += cliIn.getText() + "\n";
            Object o = ScriptEngine.getInstance().executePreface(cliIn.getText());
            t += o.toString() + "\n";
            cliOut.setText(t);
            cliIn.setText("");
        };

        CompletionProvider provider = createCompletionProvider();
        AutoCompletion ac = new AutoCompletion(provider);
        ac.install(cliIn);

        submitBtn.addActionListener(submitListener);
        cliIn.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                super.keyPressed(e);
                if (e.getKeyCode() == KeyEvent.VK_ENTER)
                    submitListener.actionPerformed(null);
            }
        });
    }

    private CompletionProvider createCompletionProvider() {

        DefaultCompletionProvider provider = new DefaultCompletionProvider();
        Set<Class<?>> set = ScriptEngine.getInstance().getFunctionDomains();
        set.forEach(cls -> {
            provider.addCompletion(new BasicCompletion(provider, cls.getSimpleName()));
            ScriptEngine.getInstance()
                    .getValidMethodsFromDomain(cls)
                    .forEach(m -> provider.addCompletion(
                            new BasicCompletion(provider, cls.getSimpleName() + "." + m.getName() + "()")));

        });

        return provider;

    }

    public JPanel getRootComponent() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setContinuousLayout(true);
        splitPane1.setDividerLocation(338);
        splitPane1.setOrientation(0);
        splitPane1.setResizeWeight(0.9);
        panel1.add(splitPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        cliOut = new JTextArea();
        cliOut.setEditable(false);
        cliOut.setFont(new Font("Consolas", cliOut.getFont().getStyle(), cliOut.getFont().getSize()));
        cliOut.setTabSize(4);
        splitPane1.setLeftComponent(cliOut);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        splitPane1.setRightComponent(panel2);
        submitBtn = new JButton();
        submitBtn.setText("Submit");
        panel2.add(submitBtn, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cliIn = new JTextArea();
        cliIn.setFont(new Font("Consolas", cliIn.getFont().getStyle(), cliIn.getFont().getSize()));
        panel2.add(cliIn, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
